sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    password: 000000
    database: 10

  wechat:
    secret: 90280898d96b5bd439eb79c5d450d243
    appid: wxc6e8d13478018daa

